BOT_TOKEN:
  - ODI0ODEyNjc5MDI1MjYyNjAz.GCV8De.zlKtebmpwR_c6oBLZ9re4krCPjKlnSpQ7YpqI0
  #- ODk1NTEyMDExxxxxxxxxxxxxxxxxxxxx
CHANNEL_ID:
  - 1062114736029843486

MODE: repost
REPLY: Y
SIMSIMI_LANG: en
DELAY: 30
DEL_AFTER:
REPOST_LAST_CHAT: 100
