BOT_TOKEN:
  - ODI0ODEyNjc5MDI1MjYyNjAz.GrzZg_.hWGzCpNDxoRZTBOiZG2AHtoqk-di3PpLrcEJGw
  #- ODk1NTEyMDExxxxxxxxxxxxxxxxxxxxx
CHANNEL_ID:
  - 1062114736029843486

MODE: repost
REPLY: Y
SIMSIMI_LANG: en
DELAY: 10
DEL_AFTER:
REPOST_LAST_CHAT: 100
